# Don't print a new line at the start of the prompt
add_newline = false

# Use custom format
format = """
[┌───────────────────>](#FFA500)$git_branch$git_status
[│](#FFA500)  $directory
[└─> $username@$hostname λ](#FFA500) """

#success_symbol = "[λ](#FFA500)"

[username]
show_always = true
format = "[$user]($style)"
style_user = "bold yellow"

[hostname]
ssh_only = false
format = "[$hostname]($style)"
style = "bold green"

[git_branch]
format = "\n[│](#FFA500)  [$symbol$branch]($style) "

[directory]
truncate_to_repo = false

[time]
disabled = true
format = "\n[│](#FFA500)    [$time]($style)"
use_12hr = true
